### ISSUE TITLE
mqtt-clock: Regression in error checks after agent setup

### ISSUE THREAD

**Issue by penguineer** [penguineer/mqtt-tools#8]
https://github.com/penguineer/mqtt-tools/blob/055f43585320db09efc1f500f6e4c1d04bd3becd/mqtt-clock.c#L226

The checking mechanism for agent setup has changed. Instead of the agent pointer, the ret value from setup calls needs to be checked in order to determine if the loop should be executed.

The bug has been introduced in a1a5126f99c75e17eaf4fb34658ae7ffccc84747.

**Comment by penguineer** [comment]
What would be a good structure to test against these errors? Some flag to trigger error responses from function calls?

**Comment by LeSpocky** [comment]
This variable `run` makes no sense at all currently. If you want to make sure `mosqagent_close_agent()` is called after your infinite loop, create a signal handler which can change `run`, but its scope has to be broader then. ;-)

**Comment by penguineer** [comment]
Since #20 the run variable makes sense.
